name: Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.134.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            resources
          key: hugo-${{ env.HUGO_VERSION }}-${{ hashFiles('hugo.toml') }}
          restore-keys: |
            hugo-${{ env.HUGO_VERSION }}-

      - name: Install Node dependencies (theme dev only)
        run: |
          if [ -f package.json ]; then npm ci --legacy-peer-deps; fi

      - name: Build site
        run: |
          echo "Repository contents:" && ls -1
          test -f hugo.toml || (echo "hugo.toml not found in repo root" && exit 1)
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
